version: '3.9'

services:
  backend:
    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-6.0.0}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
    environment:
      VIRTUAL_HOST: sepolia.explorer.treydongroup.com
      VIRTUAL_PORT: 4000
      VIRTUAL_PATH: ~^/(api|socket|sitemap.xml|auth/auth0|auth/auth0/callback|auth/logout)
